menu:
  Blog: /
  Tags: /tags
  Archive: /archives
  About: /about

favicon: /favicon.png
logo: /favicon.png

# Comment
gitalk:
  enable: false # true
  clientID: '' # GitHub Application Client ID
  clientSecret: '' # Client Secret
  repo: '' # Repository name
  owner: '' # GitHub ID
  admin: '' # GitHub ID
  distractionFreeMode: false # true

# 访问量统计(不蒜子)
busuanzi: true

# 是否启用搜索
search: true

# Copyright Infomation
startyear: 2019

# 是否在文章中显示上一篇/下一篇
prev_next: true

# less目录
less:
  paths: ['source/css']